package com.narscala.logic.inference

import com.narscala.logic.grammar.*;
import com.narscala.logic.semantics.TruthValue;
 
rule "Revision - Judgement"
salience 0
    when
        $a          : Judgement ( ) // TODO: Goal
        $b          : Judgement ( this != $a ) // TODO: Goal
        $aterm      : Term ( this == $a.term && this == $b.term )
    then
        // insert( new Judgement($aterm, scala.None$.MODULE$, TruthValue.revision($a.truth, $b.truth) ) );
end